services:
  - type: web
    name: sqwirex-webdev-lab2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5